#!/bin/sh

# Perform ad-hoc aggregations of snowfall.

START_DATE="2020-03-01 12"
FINISH_DATE="2020-04-01 12"
START_DATE_EPOCH=`date -u --date="${START_DATE}:00:00" +%s`
FINISH_DATE_EPOCH=`date -u --date="${FINISH_DATE}:00:00" +%s`
AGGREGATE_SECONDS=$((FINISH_DATE_EPOCH-START_DATE_EPOCH))
AGGREGATE_HOURS=$((AGGREGATE_SECONDS/3600))
echo "$START_DATE to $FINISH_DATE is $AGGREGATE_HOURS hours."
export DATE_YYYYMMDDHH="${FINISH_DATE:0:4}${FINISH_DATE:5:2}${FINISH_DATE:8:2}${FINISH_DATE:11:2}"
echo $DATE_YYYYMMDDHH
export DURATION_HOURS=24
export EXTENDED_COLORS=1
#export FORCE_SEASONAL=1
export AGGREGATE_HOURS
idl -rt=aggregate_snowfall_v2.sav
